version: 0.2
            
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2) 
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - docker build -t ${Repository}:${TAG} .
      - docker tag ${Repository}:${TAG} ${RepositoryURI}/${Repository}:${TAG}
  post_build:
    commands:
      - docker push ${RepositoryURI}/${Repository}:${TAG}
      - printf '{"imageUri":"%s/%s:%s"}' ${RepositoryURI} ${Repository} ${TAG} > build.json
artifacts:
  files:
    - build.json
    - configuration.json
    - template.json
  name: myname
  discard-paths: yes

