version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo awscli installed and version `aws --version`
      - echo logging in to AWS ECR..
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - REPOSITORY_URI=802878444238.dkr.ecr.us-west-2.amazonaws.com/poc-cicd-repository
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}  
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t 802878444238.dkr.ecr.us-west-2.amazonaws.com/poc-cicd-repository:$IMAGE_TAG .
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - echo logging in to AWS ECR..
      - $(aws ecr get-login --no-include-email --region us-west-2)  
      - docker push 802878444238.dkr.ecr.us-west-2.amazonaws.com/poc-cicd-repository:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"httpd-containers","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: 
      - imagedefinitions.json
      - configuration.json
      - template.json
    discard-paths: yes
