version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py --user
      - export PATH=~/.local/bin:$PATH
      - source ~/.bash_profile
      - echo PIP version `pip --version`
      - pip install awscli --upgrade --user
      - echo awscli installed and version `aws --version`
      - echo logging in to AWS ECR...
      - aws ecr get-login --region us-west-2
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t 802878444238.dkr.ecr.us-west-2.amazonaws.com/poc-cicd-repository:latest .
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 802878444238.dkr.ecr.us-west-2.amazonaws.com/poc-cicd-repository:latest
